biryong/competition/urls.py
# chat/urls.py
from django.urls import path

from biryong.competition.views import join_match_fetch, join_match_redirect, match, real_time

app_name = 'competition'

urlpatterns = [
    path("match/<int:pk>/", match, name="match"),
    path("join_match_fetch/<int:pk>/", join_match_fetch, name="join_match_fetch"),
    path("join_match_redirect/<int:pk>/", join_match_redirect, name="join_match_redirect"),
    path("real_time/", real_time, name="real_time"),
]

biryong/quiz/urls.py
from django.urls import path

from biryong.quiz.views import detail, quiz_list, quiz_list_info

app_name = "quiz"
urlpatterns = [
    path("", view=quiz_list, name="list"),
    path("detail/<int:pk>/", view=detail, name="detail"),
    path("info/", view=quiz_list_info, name="info"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.static import serve
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from config.auth_views import login, logout
from config.views import (
    get_real_time_info_json,
    home,
    joining_players,
    joining_players_json,
    olympic_chat,
    twitch_chat,
)

urlpatterns = [
    path("", home, name="home"),
    path("get_real_time_info_json/", get_real_time_info_json, name="get_real_time_info_json"),

    path('joining_players/', joining_players, name='joining_players'),
    path('joining_players_json/', joining_players_json, name='joining_players_json'),

    path('olympic_chat/', olympic_chat, name='olympic_chat'),
    path('twitch_chat/', twitch_chat, name='twitch_chat'),
    path("quiz/", include("biryong.quiz.urls", namespace="quiz")),

    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path(settings.ADMIN_URL, admin.site.urls),
    path("kakao/", include("config.auth_urls", namespace="kakao")),
    path("users/", include("biryong.users.urls", namespace="users")),

    path("smalltalk/", include("biryong.smalltalk.urls", namespace="smalltalk")),
    path("competition/", include("biryong.competition.urls", namespace="competition")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    re_path(r'^staticfiles/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
            }),
]  # TEMPROARY!!!!!

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

biryong/quiz/models.py
from django.db import models

from biryong.users.models import User

# Create your models here.

POINT_CHOICES = (
    (30, 30), (40, 40), (50, 50)
)


class Quiz(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    description_image = models.ImageField(
        upload_to="quizs", null=True, blank=True)
    genre = models.CharField(max_length=100)
    point = models.IntegerField(choices=POINT_CHOICES)
    solved = models.BooleanField(default=False)
    answer = models.TextField()
    answer_image = models.ImageField(
        upload_to="quizs", null=True, blank=True)

    solver = models.ForeignKey(
        User, related_name="solved_quizs", on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

biryong/quiz/forms.py
from django import forms

from biryong.quiz.models import Quiz


class SolveForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ('solver',)

biryong/quiz/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import redirect, render

from biryong.quiz.forms import SolveForm
from biryong.quiz.models import Quiz
from biryong.users.models import User


def get_quiz_info():
    top3_players = User.objects.filter(join_quiz=True).order_by('-solved_point')[:3]
    top3_players_info = [{
        "thumbnail_image_url": player.thumbnail_image_url,
        "nickname": player.nickname,
        "solved_point": player.solved_point
    } for player in top3_players]

    other_players = User.objects.filter(join_quiz=True).order_by('-solved_point')[3:]
    other_players_info = [{
        "thumbnail_image_url": player.thumbnail_image_url,
        "nickname": player.nickname,
        "solved_point": player.solved_point
    } for player in other_players]

    solved_quizs = Quiz.objects.filter(solved=True)
    solved_quizs_pk = [quiz.pk for quiz in solved_quizs]
    quizs = Quiz.objects.all().order_by('pk')
    quiz_info = {
        "quizs": quizs,
        "top3_players_info": top3_players_info,
        "other_players_info": other_players_info,
        "solved_quizs_pk": solved_quizs_pk
    }
    return quiz_info


@login_required
def quiz_list(request):
    quiz_info = get_quiz_info()
    return render(request, 'quiz.html', context=quiz_info)


@login_required
def quiz_list_info(request):
    quiz_info = get_quiz_info()
    quiz_info.pop("quizs")
    return JsonResponse(quiz_info)


@staff_member_required
def detail(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    if request.method == "GET":
        solve_form = SolveForm(instance=quiz)
        return render(request, 'quiz_detail.html', context={"quiz": quiz, "solve_form": solve_form})
    elif request.method == "POST":
        solve_form = SolveForm(request.POST, instance=quiz)
        if solve_form.is_valid():
            solve_form.save()
            quiz.solved = True
            solver = solve_form.cleaned_data.get("solver")
            solver.solved_point += quiz.point
            solver.save()
            print(solver, "SOVLE!!!!!!!!!")
            quiz.save()
        return redirect('quiz:list')

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description"
          content="This is the TRACER for DDSHS project" />
    <meta name="author"
          content="mjthepollo" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    <title>{% block title %}DDSHS e-Olympic{% endblock title %}</title>
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
        integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer" />
  <link href="{% static 'css/project.css' %}" rel="stylesheet" />
  {% block css %}
  {% endblock css %}
  <script>
    let vh = window.innerHeight * 0.01;
    document.documentElement.style.setProperty("--vh", `${vh}px`);
    let vw = window.innerWidth * 0.01;
    document.documentElement.style.setProperty("--vw", `${vw}px`);
    window.addEventListener("resize", () => {
      let vh = window.innerHeight * 0.01;
      document.documentElement.style.setProperty("--vh", `${vh}px`);
      let vw = window.innerWidth * 0.01;
      document.documentElement.style.setProperty("--vw", `${vw}px`);
    });
  </script>
  <script defer
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
        integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>
  <script defer src="{% static 'js/project.js' %}"></script>
  {% block javascript %}
  {% endblock javascript %}
</head>
<body>
  {% block header %}
  <header><a href = "{% url 'home' %}"><img class="olympic-logo" src="{% static 'images/olympic_rings.svg' %}"/></a></header>
  {% endblock header %}
  {% block content %}
  {% endblock content %}
  {% block modal %}
  {% endblock modal %}
  {% block inline_javascript %}
  {% endblock inline_javascript %}
</body>
</html>

templates/base_with_banner.html
{% load static i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description"
          content="This is the TRACER for DDSHS project" />
    <meta name="author"
          content="mjthepollo" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">
    <title>{% block title %}DDSHS e-Olympic{% endblock title %}</title>
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
        integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer" />
  <link href="{% static 'css/project.css' %}" rel="stylesheet" />
  <link href="{% static 'css/banner.css' %}" rel="stylesheet" />
  {% block css %}
  {% endblock css %}
  <script>
    let vh = window.innerHeight * 0.01;
    document.documentElement.style.setProperty("--vh", `${vh}px`);
    let vw = window.innerWidth * 0.01;
    document.documentElement.style.setProperty("--vw", `${vw}px`);
    window.addEventListener("resize", () => {
      let vh = window.innerHeight * 0.01;
      document.documentElement.style.setProperty("--vh", `${vh}px`);
      let vw = window.innerWidth * 0.01;
      document.documentElement.style.setProperty("--vw", `${vw}px`);
    });
  </script>
  <script defer
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
        integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>
  <script defer src="{% static 'js/project.js' %}"></script>
  {% block javascript %}
  {% endblock javascript %}
</head>
<body>
  <a id="banner" href="{% url 'competition:real_time' %}"><span id="banner__content">실시간 보러가기</span><span id="banner__click">Click!</span></a>
  {% block header %}
  <header><a href = "{% url 'home' %}"><img class="olympic-logo" src="{% static 'images/olympic_rings.svg' %}"/></a></header>
  {% endblock header %}
  {% block content %}
  {% endblock content %}
  {% block modal %}
  {% endblock modal %}
  <script src="{% static 'js/set_banner.js' %}" type="text/javascript"></script>
  {% block inline_javascript %}
  {% endblock inline_javascript %}
</body>
</html>

templates/expect_winner.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link href="{% static 'css/vote.css' %}" rel="stylesheet" />
{% endblock css%}
{% block header %}
<header>
    <a href="{% url 'home' %}"><img class="team_logo" src="{% static 'images/team1.png' %}"></a>
    <div class="vs">vs</div>
    <a href="{% url 'home' %}"><img class="team_logo" src="{% static 'images/team2.png' %}"></a>
</header>
{% endblock header %}
{% block content %}
<h1>{{competition.number}}경기 승부예측</h1>
<div class="vote_table">
    {% include 'modules/players_table.html' %}
</div>
<div class="expect_win_info">
    <a class="vote team1_vote shadow" href="{% url 'vote_expected_winner' competition.pk competition.team1.pk %}">{{competition.team1.name}}</a>
    <div class="win_rate shadow">
        <div class="win_rate_bar team1_win_rate_bar" style="width:{{team1_expectors_rate}}%;">{% if team1_expectors_count != 0 %}{{team1_expectors_count}}명{% endif %}</div>
        <div class="win_rate_bar team2_win_rate_bar" style="width:{{team2_expectors_rate}}%;">{% if team2_expectors_count != 0 %}{{team2_expectors_count}}명{% endif %}</div>
    </div>
    <a class="vote team2_vote shadow" href="{% url 'vote_expected_winner' competition.pk competition.team2.pk %}">{{competition.team2.name}}</a>
</div>
{% endblock content %}

templates/home.html
{% extends "base_with_banner.html" %}
{% load static %}
{% block css %}
<link href="{% static 'css/home.css' %}" rel="stylesheet" />
{% endblock css%}
{% block content %}
<div class="main-content-container">
    <div class="container timetable-container">
        <ul class="timetable-content">
            {% for competition in competitions %}
            <li class="timetable-content__li">
                <span class="timetable-content__li__time">{{competition.time_string}}</span>
                <div class="timetable-content__li__title">{{competition.name}}</div>
                <div class="timetable-content__li__actions">
                {% if competition.joinable %}
                <button class="participate-match" onclick="window.location='{% url 'competition:match' competition.pk %}'">경기 참가하기</button>
                {% else %}
                <button class="match-results" onclick="window.location='{% url 'competition:match' competition.pk %}'">결과 보러가기</button>
                {% endif %}
                {% if competition.real_time %}
                <button class="live-broadcast" onclick="window.location='{% url 'competition:real_time' %}'">• 실시간</button>
                {% endif %}
            </div>
          </li>
        {% endfor %}
        </ul>
      </div>
</div>
{% endblock content %}
{% block inline_javascript %}
{% endblock inline_javascript %}

templates/login.html
{% load static i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description"
          content="This is the TRACER for DDSHS project" />
    <meta name="author"
          content="mjthepollo" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    <title>
      {% block title %}
      biryong
    {% endblock title %}
  </title>
  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
          integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
  <link href="{% static 'css/project.css' %}" rel="stylesheet" />
  {% endblock css %}
<!-- Le javascript
    ================================================== -->
{# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
  <script defer
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
        integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>
  <script defer src="{% static 'js/project.js' %}"></script>
  {% endblock javascript %}
</head>
<body>
    <h1>DDSHS</h1>
    <p><a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">카카오톡으로 로그인하고 시작하기</a></p>
</body>
</html>

templates/match.html
{% extends "base_with_banner.html" %}
{% load static %}
{% block title %}DDSHS e-Olympic [{{competition.name}}]{% endblock title %}
{% block css %}
<link href="{% static 'css/match.css' %}" rel="stylesheet" />
{% endblock css%}
{% block content %}
  <div class="container match-container">
    <div class="match-header">
      <div class="match-header__left">
        <div class="match-header__time">{{competition.time_string}}</div>
        <div class="match-header__title">{{competition.name}}</div>
      </div>
      {% if user.is_authenticated %}
        {% if competition.joinable %}
          <button class="match-header__button green_button" onclick="window.location='{% url 'competition:join_match_redirect' competition.pk %}'">참가 신청하기</button>
        {% endif %}
      {% else %}
      <button class="match-header__button yellow_button" onclick="window.location='{% url 'login' %}'">참가 신청하기(로그인)</button>
      {% endif %}
    </div>
    <div class="match-content">
      {{competition.description|linebreaksbr}}
      {% if competition.discord_link %}
      <a class="additional_link" href="{{competition.discord_link}}" target="_blank"><img src="{% static 'images/discord.svg' %}">{{competition.discord_link}}</a>
      {% endif %}
      {% if competition.game_link%}
      <a class="additional_link" href="{{competition.game_link}}" target="_blank"><img src="{% static 'images/game.png' %}">{{competition.game_link}}</a>
      {% endif %}
    </div>
    <div class="match-participant">
      {% if competition.joinable %}
      <div class="match-participant__title">참가하는 사람</div>
      <div class="match-participant__people">
        {% for player in competition.active_players %}
        <img class="match-participant__people__image" src="{{player.user.thumbnail_image_url}}"/>
        {% endfor %}
      </div>
      {% else %}
      <div class="match-participant__title">참가한 사람</div>
      <div class="match-participant__people">
        {% for player in competition.players.all %}
        <img class="match-participant__people__image" src="{{player.user.thumbnail_image_url}}"/>
        {% endfor %}
      </div>
      {% endif %}
      <!-- <button class="match-participant__button">참가 신청하기</button> -->
    </div>
  </div>
{% endblock content%}
</html>

templates/quiz.html
{% extends "base_with_banner.html" %}
{% load static %}
{% block css %}
<link href="{% static 'css/quiz.css' %}" rel="stylesheet" />
{% endblock css%}
{% block content %}
<div class="main-content-container">
    <div class="top3_players">
        {% for player in top3_players_info %}
        <div class="top3_player">
            <div class="rank">{{ forloop.counter }}등</div>
            <img src="{{player.thumbnail_image_url}}">
            <span class="player_name">{{ player.nickname }}</span>
            <span class="player_score">{{ player.solved_point }}</span>
        </div>
        {% endfor %}
    </div>
    <div class='other_players'>
        {% for player in other_players_info %}
        <div class="other_player">
            <img src="{{player.thumbnail_image_url}}">
            <span class="player_name">{{ player.nickname }}</span>
            <span class="player_score">{{ player.solved_point }}</span>
        </div>
        {% endfor %}
    </div>
    <div class="quizs">
        {% for quiz in quizs %}
            {% if user.is_staff %}
            <a class='quiz {% if quiz.pk in solved_quizs_pk %}solved{% endif %}' href="{% url 'quiz:detail' quiz.pk %}" data-pk="{{quiz.pk}}">
                <div class="genre">{{quiz.genre}}</div>
                <div class="name">{{quiz.name}}</div>
                <div class="point">{{quiz.point}}</div>
            </a>
            {% else %}
            <div class="quiz {% if quiz.pk in solved_quizs_pk %}solved{% endif %}" data-pk="{{quiz.pk}}">
                <div class="genre">{{quiz.genre}}</div>
                <div class="name">{{quiz.name}}</div>
                <div class="point">{{quiz.point}}</div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock content %}
{% block inline_javascript %}
<script src="{% static 'js/quiz_list_info.js' %}"></script>
{% endblock inline_javascript %}

templates/set_additional_info.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link href="{% static 'css/set_additional_info.css' %}" rel="stylesheet" />
{% endblock css%}
{% block header %}
<header>
    <a href="{% url 'home' %}"><img class="team_logo" src="{% static 'images/team1.png' %}"></a>
    <div class="vs">vs</div>
    <a href="{% url 'home' %}"><img class="team_logo" src="{% static 'images/team2.png' %}"></a>
  </header>
{% endblock header %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <span>응원팀 설정</span>
        {{additional_info_form.support_team}}
    </div>
    <div class='mb-3'>
        <span>응원 메세지 설정</span>
        {{additional_info_form.cheer_message}}
    </div>
    <div class='mb-3'>    
        <span>트위치 아이디 설정</span>
        {{additional_info_form.twitch_id}}
    </div>
    <button class="kakao-box">정보 업데이트</button>
</form>
{% endblock content %}

templates/team1_chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">
    <link href="{% static 'css/project.css' %}" rel="stylesheet" />
    <link href="{% static 'css/team_chat.css' %}" rel="stylesheet" />
    <title>Team1Chat</title>
  </head>
  <body>
    <div id="team1_chat" class="shadow">
      <div class="chat-header">GOAT</div>
      <div class="chat-container"></div>
    </div>
  </body>
  <script type='module' src="{% static 'js/team1_chat.js' %}"></script>
</html>

templates/team2_chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link href="{% static 'css/project.css' %}" rel="stylesheet" />
    <link href="{% static 'css/team_chat.css' %}" rel="stylesheet" />
    <title>Team2Chat</title>
  </head>
  <body>
    <div id="team2_chat" class="shadow">
      <div class="chat-header">ZI존</div>
      <div class="chat-container"></div>
    </div>
  </body>
  <script type="module" src="{% static 'js/team2_chat.js' %}"></script>
</html>

templates/team_supporters.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link href="{% static 'css/team_supporters.css' %}" rel="stylesheet" />
{% endblock css%}
{% block header %}
<header>
    <a href="{% url 'home' %}"><img class="team_logo" src="{% static 'images/team1.png' %}"></a>
    <div class="vs">vs</div>
    <a href="{% url 'home' %}"><img class="team_logo" src="{% static 'images/team2.png' %}"></a>
  </header>
{% endblock header %}
{% block content %}
    <div class='supporters {{class}}'>
        {% for supporter in supporters %}
            <div class="cheer_message">
                <img class="user_thumbnail" src="{{ supporter.thumbnail_image_url }}">
                <span class="supporter_name">{{supporter.nickname}}</span>
                <div class="supporter_message_container">
                    <p class="supporter_message">{{supporter.cheer_message}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/twitch_chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">
    <link href="{% static 'css/project.css' %}" rel="stylesheet" />
    <link href="{% static 'css/team_chat.css' %}" rel="stylesheet" />
    <title>TwitchChat</title>
  </head>
  <body>
    <iframe id="chat_embed" src="https://www.twitch.tv/embed/mjthepollo/chat?parent=minbungs.site" height="500" width="350"></iframe>
  </body>
  <script type="text/javascript"></script>
</html>

templates/vote_MVP_and_MEP.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link href="{% static 'css/vote.css' %}" rel="stylesheet" />
{% endblock css%}
{% block header %}
<header>
    <a href="{% url 'home' %}"><img class="team_logo" src="{% static 'images/team1.png' %}"></a>
    <div class="vs">vs</div>
    <a href="{% url 'home' %}"><img class="team_logo" src="{% static 'images/team2.png' %}"></a>
</header>
{% endblock header %}
{% block content %}
<h1>MVP/MEP 선정</h1>
<h3>MVP(Most Valuable Player) 최고의 실력을 뽐낸 선수</h3>
<h3>MEP(Most Entertaining Player) 최고로 경기를 재미있게 만들어준 선수</h3>
<div class="vote_table">
    {% include "modules/MEP_vote.html" with team=team1 %}
    {% include "modules/MVP_vote.html" with team=team1 %}
    <div class='player_table shadow'>
        <div class="team1_header">{{team1.name}}</div>
        <div class="team2_header">{{team2.name}}</div>
        {% for player in all_players %}
        {% if not forloop.counter|divisibleby:2 %}
        <div class="player_info">
            <img class="position" src="{{player.position_image_url}}">
            <img class="tier" src="{{player.tier_image_url}}">
            <span class="nickname">{{player.nickname}}</span>
            <span class="name">{{player.name}}</span>
        </div>
        {% else %}
        <div class="player_info">
            <span class="name">{{player.name}}</span>
            <span class="nickname">{{player.nickname}}</span>
            <img class="tier" src="{{player.tier_image_url}}">
            <img class="position" src="{{player.position_image_url}}">
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% include "modules/MVP_vote.html" with team=team2 %}
    {% include "modules/MEP_vote.html" with team=team2 %}
</div>
{% endblock content %}

templates/vote_POG.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link href="{% static 'css/vote.css' %}" rel="stylesheet" />
{% endblock css%}
{% block header %}
<header>
    <a href="{% url 'home' %}"><img class="team_logo" src="{% static 'images/team1.png' %}"></a>
    <div class="vs">vs</div>
    <a href="{% url 'home' %}"><img class="team_logo" src="{% static 'images/team2.png' %}"></a>
</header>
{% endblock header %}
{% block content %}
<h1>{{competition.number}}경기 POG 선정</h1>
<div class="vote_table">
    {% include 'modules/POG_vote.html' with team=competition.team1 %}
    {% include 'modules/players_table.html' %}
    {% include 'modules/POG_vote.html' with team=competition.team2 %}
</div>
{% endblock content %}